# Stubs for usb (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.


# Names in __all__ with no definition:
#   backend
#   control
#   core
#   legacy
#   libloader
#   util
