# Stubs for usb._debug (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def methodtrace(logger: Any): ...
def functiontrace(logger: Any): ...
