# Stubs for usb._interop (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# Names in __all__ with no definition:
#   _next
#   _reduce
#   _set
#   _update_wrapper
