# Stubs for usb._lookup (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

descriptors: Any
device_classes: Any
interface_classes: Any
ep_attributes: Any
MAX_POWER_UNITS_USB2p0: int
MAX_POWER_UNITS_USB_SUPERSPEED: int
