# Stubs for usb.util (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

DESC_TYPE_DEVICE: int
DESC_TYPE_CONFIG: int
DESC_TYPE_STRING: int
DESC_TYPE_INTERFACE: int
DESC_TYPE_ENDPOINT: int
ENDPOINT_IN: int
ENDPOINT_OUT: int
ENDPOINT_TYPE_CTRL: int
ENDPOINT_TYPE_ISO: int
ENDPOINT_TYPE_BULK: int
ENDPOINT_TYPE_INTR: int
CTRL_TYPE_STANDARD: Any
CTRL_TYPE_CLASS: Any
CTRL_TYPE_VENDOR: Any
CTRL_TYPE_RESERVED: Any
CTRL_RECIPIENT_DEVICE: int
CTRL_RECIPIENT_INTERFACE: int
CTRL_RECIPIENT_ENDPOINT: int
CTRL_RECIPIENT_OTHER: int
CTRL_OUT: int
CTRL_IN: int
SPEED_LOW: int
SPEED_FULL: int
SPEED_HIGH: int
SPEED_SUPER: int
SPEED_UNKNOWN: int

def endpoint_address(address: Any): ...
def endpoint_direction(address: Any): ...
def endpoint_type(bmAttributes: Any): ...
def ctrl_direction(bmRequestType: Any): ...
def build_request_type(direction: Any, type: Any, recipient: Any): ...
def create_buffer(length: Any): ...
def find_descriptor(desc: Any, find_all: bool = ..., custom_match: Optional[Any] = ..., **args: Any): ...
def claim_interface(device: Any, interface: Any) -> None: ...
def release_interface(device: Any, interface: Any) -> None: ...
def dispose_resources(device: Any) -> None: ...
def get_langids(dev: Any): ...
def get_string(dev: Any, index: Any, langid: Optional[Any] = ...): ...
