# Stubs for rx.concurrency.mainloopscheduler.geventscheduler (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rx.concurrency.schedulerbase import SchedulerBase
from typing import Any, Optional

gevent: Any
log: Any

class GEventScheduler(SchedulerBase):
    def __init__(self) -> None: ...
    def schedule(self, action: Any, state: Optional[Any] = ...): ...
    def schedule_relative(self, duetime: Any, action: Any, state: Optional[Any] = ...): ...
    def schedule_absolute(self, duetime: Any, action: Any, state: Optional[Any] = ...): ...
    @property
    def now(self): ...
