# Stubs for moviepy.audio.fx.all (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# Names in __all__ with no definition:
#   audio_fadein
#   audio_fadeout
#   audio_left_right
#   audio_loop
#   audio_normalize
#   volumex
