# Stubs for PIL.BdfFontFile (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import FontFile
from typing import Any

bdf_slant: Any
bdf_spacing: Any

def bdf_char(f: Any): ...

class BdfFontFile(FontFile.FontFile):
    def __init__(self, fp: Any) -> None: ...
