# Stubs for PIL.CurImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import BmpImagePlugin
from typing import Any

i8: Any
i16: Any
i32: Any

class CurImageFile(BmpImagePlugin.BmpImageFile):
    format: str = ...
    format_description: str = ...
