# Stubs for PIL.features (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

modules: Any

def check_module(feature: Any): ...
def get_supported_modules(): ...

codecs: Any

def check_codec(feature: Any): ...
def get_supported_codecs(): ...
