# Stubs for PIL.FliImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

i8: Any
i16: Any
i32: Any
o8: Any

class FliImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...
    @property
    def n_frames(self): ...
    @property
    def is_animated(self): ...
    def seek(self, frame: Any) -> None: ...
    def tell(self): ...
