# Stubs for PIL.FpxImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

i32: Any
i8: Any
MODES: Any

class FpxImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...
    fp: Any = ...
    def load(self): ...
