# Stubs for PIL.FtexImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

MAGIC: bytes
FORMAT_DXT1: int
FORMAT_UNCOMPRESSED: int

class FtexImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...
    def load_seek(self, pos: Any) -> None: ...
