# Stubs for PIL.GbrImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

i32: Any

class GbrImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...
    im: Any = ...
    def load(self) -> None: ...
