# Stubs for PIL.GribStubImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

def register_handler(handler: Any) -> None: ...

class GribStubImageFile(ImageFile.StubImageFile):
    format: str = ...
    format_description: str = ...
