# Stubs for PIL.Hdf5StubImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

def register_handler(handler: Any) -> None: ...

class HDF5StubImageFile(ImageFile.StubImageFile):
    format: str = ...
    format_description: str = ...
