# Stubs for PIL.ImageColor (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def getrgb(color: Any): ...
def getcolor(color: Any, mode: Any): ...

colormap: Any
