# Stubs for PIL.ImImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

COMMENT: str
DATE: str
EQUIPMENT: str
FRAMES: str
LUT: str
NAME: str
SCALE: str
SIZE: str
MODE: str
TAGS: Any
OPEN: Any
split: Any

def number(s: Any): ...

class ImImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...
    @property
    def n_frames(self): ...
    @property
    def is_animated(self): ...
    frame: Any = ...
    fp: Any = ...
    tile: Any = ...
    def seek(self, frame: Any) -> None: ...
    def tell(self): ...

SAVE: Any
