# Stubs for PIL.ImtImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

field: Any

class ImtImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...
