# Stubs for PIL.McIdasImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile

class McIdasImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...
