# Stubs for PIL.MspImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

i16: Any

class MspImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...

o16: Any
