# Stubs for PIL.PalmImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def build_prototype_image(): ...

Palm8BitColormapImage: Any
o8: Any
o16b: Any
