# Stubs for PIL.PcfFontFile (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import FontFile
from typing import Any

PCF_MAGIC: int
PCF_PROPERTIES: Any
PCF_ACCELERATORS: Any
PCF_METRICS: Any
PCF_BITMAPS: Any
PCF_INK_METRICS: Any
PCF_BDF_ENCODINGS: Any
PCF_SWIDTHS: Any
PCF_GLYPH_NAMES: Any
PCF_BDF_ACCELERATORS: Any
BYTES_PER_ROW: Any
i8: Any
l16: Any
l32: Any
b16: Any
b32: Any

def sz(s: Any, o: Any): ...

class PcfFontFile(FontFile.FontFile):
    name: str = ...
    toc: Any = ...
    fp: Any = ...
    info: Any = ...
    def __init__(self, fp: Any) -> None: ...
