# Stubs for PIL.PcxImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

logger: Any
i8: Any
i16: Any
o8: Any

class PcxImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...

SAVE: Any
o16: Any
