# Stubs for PIL.PixarImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

i16: Any

class PixarImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...
