# Stubs for PIL.PpmImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

b_whitespace: Any
locale_lang: Any
locale_enc: Any
MODES: Any

class PpmImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...
