# Stubs for PIL.SgiImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

i8: Any
o8: Any
i16: Any

class SgiImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...
