# Stubs for PIL.TarIO (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ContainerIO
from typing import Any

class TarIO(ContainerIO.ContainerIO):
    def __init__(self, tarfile: Any, file: Any) -> None: ...
