# Stubs for PIL.TgaImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

i8: Any
i16: Any
MODES: Any

class TgaImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...

o8: Any
o16: Any
o32: Any
SAVE: Any
