# Stubs for PIL.TiffTags (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class TagInfo:
    def __new__(cls, value: Optional[Any] = ..., name: str = ..., type: Optional[Any] = ..., length: int = ..., enum: Optional[Any] = ...): ...
    def cvt_enum(self, value: Any): ...

def lookup(tag: Any): ...

BYTE: int
ASCII: int
SHORT: int
LONG: int
RATIONAL: int
UNDEFINED: int
SIGNED_RATIONAL: int
DOUBLE: int
TAGS_V2: Any
TAGS: Any
TYPES: Any
LIBTIFF_CORE: Any
