# Stubs for PIL.WalImageFile (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import __builtin__
from typing import Any

builtins = __builtin__
i32: Any

def open(filename: Any): ...

quake2palette: bytes
