# Stubs for PIL.WebPImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile

class WebPImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...
