# Stubs for PIL.WmfImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

long = int

def register_handler(handler: Any) -> None: ...

class WmfHandler:
    bbox: Any = ...
    def open(self, im: Any) -> None: ...
    def load(self, im: Any): ...

word: Any
short: Any
dword: Any

class WmfStubImageFile(ImageFile.StubImageFile):
    format: str = ...
    format_description: str = ...
