# Stubs for PIL.XbmImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

xbm_head: Any

class XbmImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...
