# Stubs for PIL.XpmImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

xpm_head: Any

class XpmImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...
    fp: Any = ...
    def load_read(self, bytes: Any): ...
