# Stubs for PIL.XVThumbImagePlugin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from PIL import ImageFile
from typing import Any

o8: Any
PALETTE: bytes

class XVThumbImageFile(ImageFile.ImageFile):
    format: str = ...
    format_description: str = ...
