# Stubs for moviepy.video.compositing.concatenate (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def concatenate_videoclips(clips: Any, method: str = ..., transition: Optional[Any] = ..., bg_color: Optional[Any] = ..., ismask: bool = ..., padding: int = ...): ...

concatenate: Any
