# Stubs for moviepy.video.compositing.on_color (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def on_color(clip: Any, size: Optional[Any] = ..., color: Any = ..., pos: Optional[Any] = ..., col_opacity: Optional[Any] = ...): ...
