# Stubs for rx (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .core import Observable, Observer
from .core.anonymousobservable import AnonymousObservable
from .core.anonymousobserver import AnonymousObserver
from typing import Any

config: Any
