# Stubs for rx.backpressure.stopandwait (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .controlledobservable import ControlledObservable
from .stopandwaitobservable import StopAndWaitObservable

def stop_and_wait(self): ...
