# Stubs for rx.backpressure.windowed (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .controlledobservable import ControlledObservable
from .windowedobservable import WindowedObservable
from typing import Any

def windowed(self, window_size: Any): ...
