# Stubs for louie (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from louie.dispatcher import connect as connect, disconnect as disconnect, get_all_receivers as get_all_receivers, reset as reset, send as send, send_exact as send_exact, send_minimal as send_minimal, send_robust as send_robust
from louie.plugin import Plugin as Plugin, QtWidgetPlugin as QtWidgetPlugin, TwistedDispatchPlugin as TwistedDispatchPlugin, install_plugin as install_plugin, remove_plugin as remove_plugin
from louie.sender import Anonymous as Anonymous, Any as Any
from louie.signal import All as All, Signal as Signal

# Names in __all__ with no definition:
#   dispatcher
#   error
#   plugin
#   robustapply
#   saferef
#   sender
#   signal
#   version
