# Stubs for louie.dispatcher (Python 3)
#

from louie.sender import Any
from typing import Any as Any_type

connects: int
disconnects: int
sends: int

def print_stats() -> None: ...

def reset() -> None: ...
def connect(receiver: Any_type, signal: Any_type = ..., sender: Any_type = ..., weak: bool = ...) -> None: ...
def disconnect(receiver: Any_type, signal: Any_type = ..., sender: Any_type = ..., weak: bool = ...) -> None: ...
def get_receivers(sender: Any_type = ..., signal: Any_type = ...): ...
def live_receivers(receivers: Any_type) -> None: ...
def get_all_receivers(sender: Any_type = ..., signal: Any_type = ...) -> None: ...
def send(signal: Any_type = ..., sender: Any_type = ..., *arguments: Any_type, **named: Any_type): ...
def send_minimal(signal: Any_type = ..., sender: Any_type = ..., *arguments: Any_type, **named: Any_type): ...
def send_exact(signal: Any_type = ..., sender: Any_type = ..., *arguments: Any_type, **named: Any_type): ...
def send_robust(signal: Any_type = ..., sender: Any_type = ..., *arguments: Any_type, **named: Any_type): ...
