# Stubs for louie.robustapply (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

IM_FUNC: str
FUNC_CODE: str

def function(receiver: Any): ...
def robust_apply(receiver: Any, signature: Any, *arguments: Any, **named: Any): ...
