# Stubs for louie.sender (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class _SENDER(type): ...

class Any:
    __metaclass__: Any = ...

class Anonymous:
    __metaclass__: Any = ...
