# Stubs for louie.sender (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any as typingAny

class _SENDER(type): ...

class Any:
    __metaclass__: typingAny = ...

class Anonymous:
    __metaclass__: typingAny = ...
