# Stubs for louie.signal (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class _SIGNAL(type): ...

class Signal:
    __metaclass__: Any = ...

class All(Signal): ...
