# Stubs for rx.disposables (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .anonymousdisposable import AnonymousDisposable
from .booleandisposable import BooleanDisposable
from .compositedisposable import CompositeDisposable
from .multipleassignmentdisposable import MultipleAssignmentDisposable
from .refcountdisposable import RefCountDisposable
from .scheduleddisposable import ScheduledDisposable
from .serialdisposable import SerialDisposable
from .singleassignmentdisposable import SingleAssignmentDisposable
