# Stubs for moviepy.audio.fx.audio_left_right (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def audio_left_right(audioclip: Any, left: int = ..., right: int = ..., merge: bool = ...): ...
