# Stubs for moviepy.audio.fx.audio_fadeout (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def audio_fadeout(clip: Any, duration: Any): ...
