# Stubs for moviepy.audio.fx.audio_fadein (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def audio_fadein(clip: Any, duration: Any): ...
