# Stubs for moviepy.audio.fx.audio_loop (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..AudioClip import concatenate_audioclips
from typing import Any, Optional

def audio_loop(audioclip: Any, nloops: Optional[Any] = ..., duration: Optional[Any] = ...): ...
