# Stubs for moviepy.audio.fx.audio_normalize (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .volumex import volumex
from typing import Any

def audio_normalize(clip: Any): ...
