# Stubs for moviepy.video.tools.credits (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def credits1(creditfile: Any, width: Any, stretch: int = ..., color: str = ..., stroke_color: str = ..., stroke_width: int = ..., font: str = ..., fontsize: int = ..., gap: int = ...): ...
