# Stubs for moviepy.video.tools.segmenting (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def findObjects(clip: Any, rem_thr: int = ..., preview: bool = ...): ...
