# Stubs for txzmq.compat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

PY3: Any
binary_string_type = bytes
binary_string_type = str

def is_nonstr_iter(v: Any): ...
