# Stubs for txzmq.test.test_reactor_shutdown (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from twisted.internet.test.reactormixins import ReactorBuilder
from typing import Any

class ZmqReactorShutdownTestCase(ReactorBuilder):
    requiredInterfaces: Any = ...
    def test_reactor_and_factory_shutdown(self) -> None: ...
    def test_reactor_shutdown(self) -> None: ...
