# Stubs for txzmq.test.test_factory (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from twisted.trial import unittest
from typing import Any

class ZmqFactoryTestCase(unittest.TestCase):
    factory: Any = ...
    def setUp(self) -> None: ...
    def test_shutdown(self) -> None: ...
