# Stubs for cycloneerr (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.



from typing import Any

class PrettyErrorHandler:
    def get_error_html(self, status_code: Any, **kwargs: Any): ...
