# Stubs for moviepy.video.fx.all (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# Names in __all__ with no definition:
#   accel_decel
#   blackwhite
#   blink
#   colorx
#   crop
#   even_size
#   fadein
#   fadeout
#   freeze
#   freeze_region
#   gamma_corr
#   headblur
#   invert_colors
#   loop
#   lum_contrast
#   make_loopable
#   margin
#   mask_and
#   mask_color
#   mask_or
#   mirror_x
#   mirror_y
#   painting
#   resize
#   rotate
#   scroll
#   speedx
#   supersample
#   time_mirror
#   time_symmetrize
