BOARD_TAG    = nano328
ARDUINO_LIBS = Adafruit_NeoPixel
USER_LIB_PATH := $(realpath .)
MONITOR_PORT = /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A7027NYX-if00-port0

include /usr/share/arduino/Arduino.mk
