# Stubs for colormath.chromatic_adaptation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

logger: Any

def apply_chromatic_adaptation(val_x: Any, val_y: Any, val_z: Any, orig_illum: Any, targ_illum: Any, observer: str = ..., adaptation: str = ...): ...
def apply_chromatic_adaptation_on_color(color: Any, targ_illum: Any, adaptation: str = ...): ...
