# Stubs for colormath.color_constants (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

CIE_E: Any
CIE_K: Any
ILLUMINANTS: Any
OBSERVERS: Any
ADAPTATION_MATRICES: Any
