# Stubs for colormath.density (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def ansi_density(color: Any, density_standard: Any): ...
def auto_density(color: Any): ...
