# Stubs for colormath.density_standards (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

VISUAL_DENSITY_THRESH: float
ANSI_STATUS_A_RED: Any
ANSI_STATUS_A_GREEN: Any
ANSI_STATUS_A_BLUE: Any
ANSI_STATUS_E_RED: Any
ANSI_STATUS_E_GREEN: Any
ANSI_STATUS_E_BLUE: Any
ANSI_STATUS_M_RED: Any
ANSI_STATUS_M_GREEN: Any
ANSI_STATUS_M_BLUE: Any
ANSI_STATUS_T_RED: Any
ANSI_STATUS_T_GREEN: Any
ANSI_STATUS_T_BLUE: Any
TYPE1: Any
TYPE2: Any
ISO_VISUAL: Any
