# Stubs for moviepy.video.io.bindings (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def PIL_to_npimage(im: Any): ...
def mplfig_to_npimage(fig: Any): ...
