# Stubs for moviepy.video.io.downloader (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def download_webfile(url: Any, filename: Any, overwrite: bool = ...) -> None: ...
