# Stubs for moviepy.video.io.gif_writers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

IMAGEIO_FOUND: bool

def write_gif_with_tempfiles(clip: Any, filename: Any, fps: Optional[Any] = ..., program: str = ..., opt: str = ..., fuzz: int = ..., verbose: bool = ..., loop: int = ..., dispose: bool = ..., colors: Optional[Any] = ..., logger: str = ...) -> None: ...
def write_gif(clip: Any, filename: Any, fps: Optional[Any] = ..., program: str = ..., opt: str = ..., fuzz: int = ..., verbose: bool = ..., withmask: bool = ..., loop: int = ..., dispose: bool = ..., colors: Optional[Any] = ..., logger: str = ...) -> None: ...
def write_gif_with_image_io(clip: Any, filename: Any, fps: Optional[Any] = ..., opt: int = ..., loop: int = ..., colors: Optional[Any] = ..., verbose: bool = ..., logger: str = ...) -> None: ...
