# Stubs for moviepy.video.io.html_tools (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..VideoClip import ImageClip, VideoClip
from .ffmpeg_reader import ffmpeg_parse_infos
from IPython.display import HTML
from typing import Any, Optional

ipython_available: bool

class HTML2(HTML):
    def __add__(self, other: Any): ...

sorry: str
templates: Any

def html_embed(clip: Any, filetype: Optional[Any] = ..., maxduration: int = ..., rd_kwargs: Optional[Any] = ..., center: bool = ..., **html_kwargs: Any): ...
def ipython_display(clip: Any, filetype: Optional[Any] = ..., maxduration: int = ..., t: Optional[Any] = ..., fps: Optional[Any] = ..., rd_kwargs: Optional[Any] = ..., center: bool = ..., **html_kwargs: Any): ...
