# Stubs for rdfdb.currentstategraphapi_test (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest

class TestSequentialUri(unittest.TestCase):
    def test_returnsSequentialUris(self) -> None: ...
