# Stubs for rdfdb.graphfile_test (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest

class TestGraphFileOutput(unittest.TestCase):
    def testMaintainsN3PrefixesFromInput(self): ...
