# Stubs for rdfdb.localsyncedgraph (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rdfdb.autodepgraphapi import AutoDepGraphApi
from rdfdb.currentstategraphapi import CurrentStateGraphApi
from rdfdb.grapheditapi import GraphEditApi
from typing import Any, Optional

class LocalSyncedGraph(CurrentStateGraphApi, AutoDepGraphApi, GraphEditApi):
    def __init__(self, files: Optional[Any] = ...) -> None: ...
    def patch(self, p: Any) -> None: ...
