# Stubs for rdfdb.rdflibpatch_literal (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest

def patch() -> None: ...

class TestDoubleOutput(unittest.TestCase):
    def testNoDanglingPoint(self) -> None: ...
