# Stubs for moviepy.video.fx.accel_decel (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def f_accel_decel(t: Any, old_d: Any, new_d: Any, abruptness: int = ..., soonness: float = ...): ...
def accel_decel(clip: Any, new_duration: Optional[Any] = ..., abruptness: float = ..., soonness: float = ...): ...
