# Stubs for moviepy.video.fx.blackwhite (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def blackwhite(clip: Any, RGB: Optional[Any] = ..., preserve_luminosity: bool = ...): ...
