# Stubs for moviepy.video.fx.crop (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def crop(clip: Any, x1: Optional[Any] = ..., y1: Optional[Any] = ..., x2: Optional[Any] = ..., y2: Optional[Any] = ..., width: Optional[Any] = ..., height: Optional[Any] = ..., x_center: Optional[Any] = ..., y_center: Optional[Any] = ...): ...
