# Stubs for moviepy.video.fx.fadein (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def fadein(clip: Any, duration: Any, initial_color: Optional[Any] = ...): ...
