# Stubs for moviepy.video.fx.fadeout (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def fadeout(clip: Any, duration: Any, final_color: Optional[Any] = ...): ...
