# Stubs for moviepy.video.fx.freeze (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def freeze(clip: Any, t: int = ..., freeze_duration: Optional[Any] = ..., total_duration: Optional[Any] = ..., padding_end: int = ...): ...
