# Stubs for moviepy.video.fx.freeze_region (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .crop import crop
from typing import Any, Optional

def freeze_region(clip: Any, t: int = ..., region: Optional[Any] = ..., outside_region: Optional[Any] = ..., mask: Optional[Any] = ...): ...
