# Stubs for moviepy.video.fx.headblur (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

headblur_possible: bool

def headblur(clip: Any, fx: Any, fy: Any, r_zone: Any, r_blur: Optional[Any] = ...): ...

doc: Any
