# Stubs for moviepy.video.fx.loop (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def loop(self, n: Optional[Any] = ..., duration: Optional[Any] = ...): ...
