# Stubs for moviepy.video.fx.lum_contrast (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def lum_contrast(clip: Any, lum: int = ..., contrast: int = ..., contrast_thr: int = ...): ...
