# Stubs for moviepy.video.fx.make_loopable (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def make_loopable(clip: Any, cross: Any): ...
