# Stubs for moviepy.video.fx.margin (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def margin(clip: Any, mar: Optional[Any] = ..., left: int = ..., right: int = ..., top: int = ..., bottom: int = ..., color: Any = ..., opacity: float = ...): ...
