# Stubs for moviepy.video.fx.mask_or (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..VideoClip import ImageClip
from typing import Any

def mask_or(clip: Any, other_clip: Any): ...
