# Stubs for moviepy.video.fx.mask_and (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..VideoClip import ImageClip
from typing import Any

def mask_and(clip: Any, other_clip: Any): ...
