# Stubs for moviepy.video.fx.mask_color (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def mask_color(clip: Any, color: Optional[Any] = ..., thr: int = ..., s: int = ...): ...
