# Stubs for moviepy.video.fx.mirror_y (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def mirror_y(clip: Any, apply_to: str = ...): ...
