# Stubs for moviepy.video.fx.mirror_x (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def mirror_x(clip: Any, apply_to: str = ...): ...
