# Stubs for moviepy.video.fx.painting (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

painting_possible: bool

def to_painting(image: Any, saturation: float = ..., black: float = ...): ...
def painting(clip: Any, saturation: float = ..., black: float = ...): ...

doc: Any
