# Stubs for moviepy.video.fx.resize (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

resize_possible: bool

def resizer(pic: Any, newsize: Any): ...

resizer: Any

def resize(clip: Any, newsize: Optional[Any] = ..., height: Optional[Any] = ..., width: Optional[Any] = ..., apply_to_mask: bool = ...): ...

doc: Any
