# Stubs for moviepy.video.fx.rotate (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

PIL_FOUND: bool

def pil_rotater(pic: Any, angle: Any, resample: Any, expand: Any): ...
def rotate(clip: Any, angle: Any, unit: str = ..., resample: str = ..., expand: bool = ...): ...
