# Stubs for moviepy.video.fx.scroll (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def scroll(clip: Any, h: Optional[Any] = ..., w: Optional[Any] = ..., x_speed: int = ..., y_speed: int = ..., x_start: int = ..., y_start: int = ..., apply_to: str = ...): ...
