# Stubs for moviepy.video.fx.speedx (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def speedx(clip: Any, factor: Optional[Any] = ..., final_duration: Optional[Any] = ...): ...
