# Stubs for moviepy.video.fx.supersample (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def supersample(clip: Any, d: Any, nframes: Any): ...
