# Stubs for moviepy.video.fx.time_symmetrize (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .time_mirror import time_mirror
from typing import Any

def time_symmetrize(clip: Any): ...
