# Stubs for PIL.OleFileIO (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .olefile import *

# Names in __all__ with no definition:
#   DEFAULT_PATH_ENCODING
#   DEFECT_FATAL
#   DEFECT_INCORRECT
#   DEFECT_POTENTIAL
#   DEFECT_UNSURE
#   DIFSECT
#   ENDOFCHAIN
#   FATSECT
#   FREESECT
#   KEEP_UNICODE_NAMES
#   MAGIC
#   MAXREGSECT
#   MAXREGSID
#   MINIMAL_OLEFILE_SIZE
#   NOSTREAM
#   OleFileIO
#   OleMetadata
#   STGTY_EMPTY
#   STGTY_LOCKBYTES
#   STGTY_PROPERTY
#   STGTY_ROOT
#   STGTY_STORAGE
#   STGTY_STREAM
#   UNKNOWN_SIZE
#   WORD_CLSID
#   enable_logging
#   isOleFile
