# Stubs for moviepy.audio.tools.cuts (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def find_audio_period(aclip: Any, t_min: float = ..., t_max: int = ..., t_res: float = ...): ...
