# Stubs for rx.internal.exceptions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class SequenceContainsNoElementsError(Exception):
    def __init__(self, msg: Optional[Any] = ...) -> None: ...

class ArgumentOutOfRangeException(ValueError):
    def __init__(self, msg: Optional[Any] = ...) -> None: ...

class DisposedException(Exception):
    def __init__(self, msg: Optional[Any] = ...) -> None: ...

class ReEntracyException(Exception):
    def __init__(self, msg: Optional[Any] = ...) -> None: ...

class CompletedException(Exception):
    def __init__(self, msg: Optional[Any] = ...) -> None: ...

class WouldBlockException(Exception):
    def __init__(self, msg: Optional[Any] = ...) -> None: ...

class InvalidOperationException(Exception):
    def __init__(self, msg: Optional[Any] = ...) -> None: ...
