# Stubs for rx.internal.extensionmethod (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def extensionmethod(base: Any, name: Optional[Any] = ..., decorator: Optional[Any] = ..., instancemethod: bool = ..., alias: Optional[Any] = ...): ...
def extensionclassmethod(base: Any, name: Optional[Any] = ..., alias: Optional[Any] = ...): ...
