# Stubs for rx.concurrency.scheduleperiodic (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class SchedulePeriodic:
    def __init__(self, scheduler: Any, period: Any, action: Any, state: Optional[Any] = ...) -> None: ...
    def tick(self, scheduler: Any, command: Any) -> None: ...
    def start(self): ...
