# Stubs for rx.concurrency.timeoutscheduler (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .schedulerbase import SchedulerBase
from typing import Any, Optional

log: Any

class TimeoutScheduler(SchedulerBase):
    def schedule(self, action: Any, state: Optional[Any] = ...): ...
    def schedule_relative(self, duetime: Any, action: Any, state: Optional[Any] = ...): ...
    def schedule_absolute(self, duetime: Any, action: Any, state: Optional[Any] = ...): ...

timeout_scheduler: Any
