# Stubs for moviepy.config (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.


from .config_defaults import FFMPEG_BINARY, IMAGEMAGICK_BINARY
from typing import Any, Optional

def try_cmd(cmd: Any): ...

success: Any
err: Any
key: Any

def get_setting(varname: Any): ...
def change_settings(new_settings: Optional[Any] = ..., filename: Optional[Any] = ...) -> None: ...
