# Stubs for moviepy.editor (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .audio.AudioClip import AudioClip, CompositeAudioClip, concatenate_audioclips
from .audio.io.AudioFileClip import AudioFileClip
from .tools import cvsecs
from .video.VideoClip import ColorClip, ImageClip, TextClip
from .video.compositing.CompositeVideoClip import CompositeVideoClip, clips_array
from .video.compositing.concatenate import concatenate, concatenate_videoclips
from .video.io.ImageSequenceClip import ImageSequenceClip
from .video.io.VideoFileClip import VideoFileClip
from .video.io.downloader import download_webfile

class VideoClip:
    def __init__(self, make_frame, duration) -> None: ...
    fps: float
    def write_videofile(self, path: str, **kw): ...
