# Stubs for moviepy.tools (Python 3)
#

from typing import Any, Optional

def sys_write_flush(s: Any) -> None: ...
def verbose_print(verbose: Any, s: Any) -> None: ...
def subprocess_call(cmd: Any, logger: str = ..., errorprint: bool = ...) -> None: ...
def is_string(obj: Any): ...
def cvsecs(time: Any): ...
def deprecated_version_of(f: Any, oldname: Any, newname: Optional[Any] = ...): ...

extensions_dict: Any

def find_extension(codec: Any): ...
