# Stubs for moviepy.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def close_all_clips(objects: str = ..., types: Any = ...) -> None: ...
